all: 
	make -C JPN
	make -C EUR
	make -C FRA
	make -C GER
	make -C ITA
	make -C SPA

clean:
	make -C JPN clean
	make -C EUR clean
	make -C FRA clean
	make -C GER clean
	make -C ITA clean
	make -C SPA clean
